//
// Created by alon on 7/31/21.
//

#ifndef WTFPROJECT_CONSTS_H
#define WTFPROJECT_CONSTS_H
#define ASCII_MNEMONIC ".asciz"
#define EXTERN_MNEMONIC ".extern"
#define ENTRY_MNEMONIC ".entry"

enum ErrorCode {GOOD = 0, GENERIC_ERROR, ASCIIZ_UNBALANCED_PARENTHESIS, ASCIIZ_MISSING_PARENTHESIS, ASCIIZ_EXTRA_TOKENS,
    ASCIZ_ILLEGAL_CHAR, MISSING_OPERAND, INVALID_LABEL,ERR_LABEL_ALREADY_DEFINED};
#endif //WTFPROJECT_CONSTS_H
