//
// Created by Ram Ben on 7/3/2021.
//

#ifndef WTFPROJECT_STATUSCODES_H
#define WTFPROJECT_STATUSCODES_H

#define LINE_OK 0
#define LINE_UNRECOGNIZED_INSTRUCTION 1

#define OPERAND_NOT_REGISTER -1
#define OPERAND_NOT_VALID_REGISTER -2

#endif //WTFPROJECT_STATUSCODES_H
